### ISSUE TITLE
Cannot save output json file 

### ISSUE THREAD

**Issue by jiaodong** [gaogaotiantian/viztracer#231]
Hi, thanks for the tool, documentation looks interesting and this is my first ever try on it.

I'm using it to profile a [Ray application](https://github.com/ray-project/ray) with multiple processes and it seems to have issue with generating json file

```
Loading trace data from processes 2/3Traceback (most recent call last):
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/click/core.py", line 1063, in main
    ctx.exit()
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/click/core.py", line 681, in exit
    raise Exit(code)
click.exceptions.Exit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/main.py", line 595, in main
    success, err_msg = ui.run()
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/main.py", line 343, in run
    return self.run_command()
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/main.py", line 449, in run_command
    return self.run_code(code, main_mod.__dict__)
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/main.py", line 366, in run_code
    exec(code, global_dict)
  File "/Users/jiaodong/Workspace/ray/release/serve_tests/workloads/deployment_graph_long_chain.py", line 177, in <module>
    main()
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/click/core.py", line 1081, in main
    sys.exit(e.exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/main.py", line 582, in exit_routine
    self.save()
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/main.py", line 563, in save
    builder.save(output_file=ofile)
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/report_builder.py", line 180, in save
    self.generate_report(f, output_format="json", file_info=file_info)
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/report_builder.py", line 162, in generate_report
    self.prepare_json(file_info=file_info)
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/report_builder.py", line 106, in prepare_json
    self.load_jsons()
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/report_builder.py", line 72, in load_jsons
    self.jsons.append(get_json(j))
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/site-packages/viztracer/report_builder.py", line 32, in get_json
    return json.loads(json_str)
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/jiaodong/anaconda3/envs/ray/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 60301313 (char 60301312)
```

**Comment by gaogaotiantian** [comment]
Hi, thanks for the issue. Is there a minimum code demo for me to reproduce this? It seems like the temporary JSON file was corrupted. Either there's some bug in my raw JSON dump code, or the subprocess created by Ray was not gracefully ended. I'm not an expert in Ray, I think I've heard people using that with `viztracer` successfully. Without any context, I just want to confirm how Ray ends its subprocesses? Is it using SIGKILL after a certain time? `viztracer` requires all the processes to generate their own trace log, which could take a while if the trace log is large.

**Comment by jiaodong** [comment]
Thanks for the quick response ! I had success with a simple ray DAG application that acts as a batch job, but ran into JSON issue for the same DAG using Ray Serve that spawns long running replicas by design, this seems to match your description regarding process termination. Let me put up a minimal example after meeting and will tag you soon today.

**Comment by jiaodong** [comment]
@gaogaotiantian i just gave it another try with a plain script that i try to profile and it actually works well :) 

I tried this on the nightly wheel of ray https://docs.ray.io/en/master/ray-overview/installation.html#daily-releases-nightlies

https://gist.github.com/jiaodong/c15837f17b8379784c97a73a2f64e038

So from my experience of trying it out for an hour, both Ray Core and Ray Serve actually can be profiled, so the issue I ran into might be the CLI script on my end. (Full script is https://sourcegraph.com/github.com/ray-project/ray/-/blob/release/serve_tests/workloads/deployment_graph_long_chain.py that executed with same ray nightly wheel)

**Comment by gaogaotiantian** [comment]
Hmm, I can't find anything obvious with the script. It would be nice to know how the json file was corrupted. I double checked the code and I don't think I left a way to easily keep and find the temporary json files. However, they should be in the `/tmp` folder somewhere, if the process did not finish. It would be nice to know if the json file was just truncated because the subprocess was interrupted, or there's some corner case that broke my json dump code. Just to let you know, to make this dump faster, I wrote my own compact JSON encoder so there could be bugs in it.

**Comment by jiaodong** [comment]
I see, thanks for the context. I will leave this issue open and see if I can update with more context once I ran into the JSON encoder issue again, but in the meantime I'm not blocked on it if I modify my workload to a different, minimal structure. Thanks for the great work on this tool ! If it works well I might recommend other developers on Ray project to use it to profile their Ray application :)

**Comment by jiaodong** [comment]
Hi @gaogaotiantian, to close the loop on this I found the answer based on your inputs -- my application has a few `ray.kill(actor)` calls that do not terminate child process gracefully, thus lead to this issue. The solution I found is quite simple but works: `subprocess.run("ray stop".split(" "))` twice at the end and give it sometime to gracefully shutdown all processes for both actors and raylets :)

**Comment by gaogaotiantian** [comment]
Yeah, the symptom seemed like a SIGKILL somewhere. I'm glad you solved this. It's interesting to see `subprocess.run("ray stop".split(" "))` instead of `subprocess.run(["ray", "stop"])`, maybe it is clearer about how the command is supposed to be?

**Comment by jiaodong** [comment]
these are equivalent and i simply used the same command in one of our tests :)
