### ISSUE TITLE
Occasional failure on Windows of tests.test_simulator.TestSimulator.test_tid_pid

### ISSUE THREAD

**Issue by gaogaotiantian** [gaogaotiantian/viztracer#26]
This occasionally happens on the github validation machine. I do not use Windows native to develop that much and I failed to reproduce this issue on my machine with some efforts. 

I suspected that this is a racing issue with multithreads.

This is a branch feature(vdb + multithread) and will not affect the main usage as long as you do not use vdb on multithread logs. However, if you are interested in the error, I would appreciate if you could take a deeper look at this. Either figure out why this happens(even fix it with a PR), or find a reliable way to reproduce this.

If you are a contributor and found this error when you PR, you can ignore it for now and re-run the validations. 

```
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.8.6\x64\Scripts\vdb.exe\__main__.py", line 7, in <module>
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\viztracer\simulator.py", line 143, in main
    sim = Simulator(s, no_clear=options.no_clear, extra_newline=options.extra_newline)
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\viztracer\simulator.py", line 29, in __init__
    self.snapshot = ProgSnapshot(json_string, self.print)
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\viztracer\prog_snapshot.py", line 177, in __init__
    if not self.load(json_string):
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\viztracer\prog_snapshot.py", line 194, in load
    self.load_event(event)
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\viztracer\prog_snapshot.py", line 220, in load_event
    self.func_trees[pid][tid].add_event(event)
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\viztracer\functree.py", line 88, in add_event
    self.curr.adopt(node)
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\site-packages\viztracer\functree.py", line 72, in adopt
    self.parent.adopt(other)
AttributeError: 'NoneType' object has no attribute 'adopt'
```

**Comment by gaogaotiantian** [comment]
It's possible that this bug is fixed by #25 . We will observe for a couple runs before closing it

**Comment by gaogaotiantian** [comment]
I think #25 fixed this. Never saw another occurrence again. Close it.

**Comment by gaogaotiantian** [comment]
We have another incident so this is not gone.

https://github.com/gaogaotiantian/viztracer/runs/1339862659?check_suite_focus=true

**Comment by gaogaotiantian** [comment]
One possible reason is Windows providing negative timestamp, which will make the root node of functree confuse. I will change the start time of root and see if this happens in the future

**Comment by gaogaotiantian** [comment]
It seems like after https://github.com/gaogaotiantian/viztracer/commit/57f8db26564feeca395df96e68bb1e8bcae6e494 this never happened again. Probably the reason is the negative timestamp from Windows. We'll close this for now and reopen if it reproduces.
