### ISSUE TITLE
Viztracer doesn't play nicely with wandb

### ISSUE THREAD

**Issue by zplizzi** [gaogaotiantian/viztracer#299]
On python 3.9, viztracer 0.15.6, and wandb 0.13.5, the following example crashes:
```
import wandb

if __name__ == "__main__":
    wandb.init()
```

Wandb is a popular machine learning logging library. 

The first couple lines are from some logging I added - it looks like wandb is trying to start a python subprocess using `-m` and that's not playing nicely with viztracer. Is it patching `python` somehow?

```
$ viztracer --min_duration 10us --ignore_c_function --ignore_frozen test.py
['/opt/venv/bin/python3.9', '-m', 'wandb', 'service', '--port-filename', '/tmp/tmpe_lmqq_8/port-15021.txt', '--pid', '15021', '--debug', '--serve-sock']
No such file as -m
proc exited with 1
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 265, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
    self._service.start()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 110, in start
    self._launch_server()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 106, in _launch_server
    assert ports_found
AssertionError
wandb: ERROR Abnormal program exit
Total Entries: 420
Use the following command to open the report:
vizviewer /opt/projects/generally_intelligent/standalone/avalon/avalon/agent/result.json
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 265, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
    self._service.start()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 110, in start
    self._launch_server()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 106, in _launch_server
    assert ports_found
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/bin/viztracer", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.9/site-packages/viztracer/main.py", line 566, in main
    success, err_msg = ui.run()
  File "/opt/venv/lib/python3.9/site-packages/viztracer/main.py", line 301, in run
    return self.run_command()
  File "/opt/venv/lib/python3.9/site-packages/viztracer/main.py", line 417, in run_command
    return self.run_code(code, main_mod.__dict__)
  File "/opt/venv/lib/python3.9/site-packages/viztracer/main.py", line 334, in run_code
    exec(code, global_dict)
  File "/opt/projects/generally_intelligent/standalone/avalon/avalon/agent/test.py", line 4, in <module>
    wandb.init()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1116, in init
    raise Exception("problem") from error_seen
Exception: problem
```

**Comment by gaogaotiantian** [comment]
Yes, viztracer patches `subprocess` library to do automatic multi-process support. This is a bug on viztracer for using `-m` in `subprocess`. I can fix this soon. In the meantime, if you don't need multi-process support, you can try to pass ``--ignore_multiprocess`` to viztracer to avoid the patching.

**Comment by gaogaotiantian** [comment]
@zplizzi this is fixed in mainline. You can test it out with `pip install git+https://github.com/gaogaotiantian/viztracer`. I tried with wandb and it worked.
