### ISSUE TITLE
vizviewer fails attempting to open with a large (3.8G) result.json.

### ISSUE THREAD

**Issue by cjw296** [gaogaotiantian/viztracer#308]
I created a large result.json with `python -m viztracer ...`, that run ended up with this message:

```
Circular buffer is full, you lost some early data, but you still have the most recent data.
    If you need more buffer, use "viztracer --tracer_entries <entry_number>"
    Or, you can try the filter options to filter out some data you don't need
    use --quiet to shut me up
```

...but a 3.8G `result.json` was produced, so thought I'd try to visualize it.

`vizviewer --server_only  result.json` looked good, but eventually gave an error from Perfetto after loading 31%: "Oops! Your WASM trace processor ran out of memory"

From the docs, I then tried:
`vizviewer  --server_only --use_external_processor result.json`

This ran for much longer before serving up an http port, but failed much more quickly in the browser, this time with:
```
Viewed on: http://xxx:10000

TypeError: Failed to fetch
TypeError: Failed to fetch
    at http://xxx:10000/v25.0-cca3e0ce7/frontend_bundle.js:113462:9
```

...but nothing in the logs visible in the console other than:

```
$ vizviewer  --server_only --use_external_processor result.json
Loading and parsing trace data, this could take a while...


Running vizviewer
You can also view your trace on http://localhost:10000
Press Ctrl+C to quit
```

**Comment by gaogaotiantian** [comment]
3.8G is pretty huge, are you using the default entry number? It is expected that WASM can't handle data this large. However, in theory, the external processor should be able to handle it. How large is your RAM? Do you still have enough memory?

**Comment by Arthur-Null** [comment]
same error here. I ran `vizviewer  --server_only --use_external_processor result.json` on a 1000G RAM server and tried on open the website on my local machine. 
It gives error message
```
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: http://localhost:10000

TypeError: Failed to fetch
TypeError: Failed to fetch
    at http://localhost:10000/v25.0-cca3e0ce7/frontend_bundle.js:113462:9

v25.0-cca3e0ce7 cca3e0ce7300e9ab1616888edfd92238fbc27378
```

The processor process on the server seems to be running normally.

**Comment by gaogaotiantian** [comment]
@Arthur-Null did you confirm that with a smaller trace file, your method(opening a remote website on local machine) works?

**Comment by Arthur-Null** [comment]
> @Arthur-Null did you confirm that with a smaller trace file, your method(opening a remote website on local machine) works?

Yes, it works on a 10M trace file.

**Comment by gaogaotiantian** [comment]
Hmm. 4G trace file is indeed huge, but perfetto claimed to be able to handle it. I'm not entirely sure whether this is an issue with perfetto or viztracer. You can probably try to open the trace file with perfetto directly(of course it requires the externel processor as well). I can do the experiment when I have some time(and I need to generate a huge trace file). If standalone Perfetto can handle this file, then I'll invesitigate if viztracer did something wrong.

**Comment by mbecker8600** [comment]
FYI, this issue is still happening. has there been any resolution to this? 

I have a 3.2G file I'm trying to open and see all the same issues mentioned before.

**Comment by gaogaotiantian** [comment]
> FYI, this issue is still happening. has there been any resolution to this?
> 
> I have a 3.2G file I'm trying to open and see all the same issues mentioned before.

Did you use `--use_external_processor`? Did you try to open the trace file with Perfetto directly instead of `vizviewer`?

**Comment by mbecker8600** [comment]
> Owner

Yeah I tried both and I got the same error that the @Arthur-Null  had

**Comment by gaogaotiantian** [comment]
If you can't open the trace file with original Perfetto, then there's nothing viztracer can do. viztracer is using a modified version of Perfetto but the key decoding ability is pure Perfetto. 4G trace is indeed huge and normally I would recommend to use filters to filter out some information, or do a less period of time. However, if you want to make this work, you can submit an issue in Perfetto repo.
