### ISSUE TITLE
Windows下vizviewer在使用被占用的端口时无法使用Ctrl+C退出

### ISSUE THREAD

**Issue by Dealizey** [gaogaotiantian/viztracer#353]
系统软件版本：
Windows 11  22H2
```powershell
(web) PS F:\> python -V
Python 3.9.12
(web) PS F:\> viztracer --version
0.15.6
```
BUG:
```powershell
(web) PS F:\***> viztracer .\test.py
Total Entries: 1000002
Use the following command to open the report:
vizviewer F:\***\result.json
(web) PS F:\***> vizviewer .\result.json -p 9901 # 此处9901是一个被占用的端口，换成其他端口就不会报错
Exception in thread Thread-1:
Traceback (most recent call last):
  File "F:\ProgramData\Miniconda3\envs\web\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "F:\ProgramData\Miniconda3\envs\web\lib\site-packages\viztracer\viewer.py", line 301, in run
    self.retcode = self.view()
  File "F:\ProgramData\Miniconda3\envs\web\lib\site-packages\viztracer\viewer.py", line 341, in view
    with VizViewerTCPServer(('0.0.0.0', self.port), Handler) as self.httpd:
  File "F:\ProgramData\Miniconda3\envs\web\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "F:\ProgramData\Miniconda3\envs\web\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。
# 此时程序卡住了，无论怎么按Ctrl+C都不会退出
```
程序卡住了，无论怎么按Ctrl+C都不会退出。这也许是一个BUG

**Comment by gaogaotiantian** [comment]
`vizviewer`的threading的lock没有处理exception的情况，导致副线程在exception的情况下始终没有释放一个主线程在等的锁。#354会修复这个问题。
