### ISSUE TITLE
Something wrong with inline joblib.Parallel

### ISSUE THREAD

**Issue by SouthernWolf123** [gaogaotiantian/viztracer#411]
There's a bug when viz tracer tracing the `joblib.Parallel` inline。
A Simple Example
Firstly, install the viztracer,joblib.
Secondly, run the follow code.
```python
from viztracer import VizTracer
from joblib import Parallel, delayed

with VizTracer(output_file="traceTmp.json") as tracer:
    def f(n):
        if n== 0 or n==1:
            return 1
        else:
            return f(n-1)+f(n-2)
    tmplist = Parallel(n_jobs=5)([delayed(f)(i) for i in range(10,20)])
print("finished")
```
Finally, We get Error like this:
```cmd
vizviewer "C:\Users\EF\Documents\code\py_code\MyCode\Dagsched\simulater\traceTmp1.json"
Traceback (most recent call last):
  File "C:\conda\envs\py12\Lib\multiprocessing\util.py", line 303, in _run_finalizers
    finalizer()
  File "C:\conda\envs\py12\Lib\multiprocessing\util.py", line 227, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\conda\envs\py12\Lib\site-packages\viztracer\viztracer.py", line 312, in exit_routine
    os.remove(self.viztmp)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'traceTmp1.json'
Traceback (most recent call last):
  File "C:\conda\envs\py12\Lib\multiprocessing\util.py", line 303, in _run_finalizers
    finalizer()
  File "C:\conda\envs\py12\Lib\multiprocessing\util.py", line 227, in __call__
    res = self._callback(*self._args, **self._kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\conda\envs\py12\Lib\site-packages\viztracer\viztracer.py", line 312, in exit_routine
    os.remove(self.viztmp)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'traceTmp1.json'
Loading finish
Total Entries: 37179
Use the following command to open the report:
```

**Comment by gaogaotiantian** [comment]
Inline VizTracer does not work with multi-processing. If you want to trace multi processing code, you have to use the CLI.
