### ISSUE TITLE
 NameError: name 'false' is not defined. Did you mean: 'False'?

### ISSUE THREAD

**Issue by timmermansjoy** [gaogaotiantian/viztracer#414]
Just using the default example on the readme with `viztracer service.py -d ` and `viztracer result.json` I get NameError: name 'false' is not defined. Did you mean: 'False'?

running on python3.12 on a M2 Mac in a virtualenv

```
Total Entries: 21                                                               
Use the following command to open the report:
vizviewer /Users/joy/jtest/mini_hal/src/display-service/secury360_mini_hal/display_service/result.json
Traceback (most recent call last):
  File "/Users/joy/jtest/mini_hal/.venv/bin/viztracer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/joy/jtest/mini_hal/.venv/lib/python3.12/site-packages/viztracer/main.py", line 655, in main
    success, err_msg = ui.run()
                       ^^^^^^^^
  File "/Users/joy/jtest/mini_hal/.venv/lib/python3.12/site-packages/viztracer/main.py", line 306, in run
    return self.run_command()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/joy/jtest/mini_hal/.venv/lib/python3.12/site-packages/viztracer/main.py", line 433, in run_command
    return self.run_code(code, main_mod.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joy/jtest/mini_hal/.venv/lib/python3.12/site-packages/viztracer/main.py", line 350, in run_code
    exec(code, global_dict)
```

**Comment by gaogaotiantian** [comment]
You should do `vizviewer result.json`, not `viztracer result.json`.
