### ISSUE TITLE
TypeError: CodeMonkey.compile() got an unexpected keyword argument '_feature_version'

### ISSUE THREAD

**Issue by seniorsolt** [gaogaotiantian/viztracer#456]
Error arised when trying to track --log_attr https://github.com/Nerogar/OneTrainer. 

(venv) PS C:\Users\Max\Desktop\OneTrainer> viztracer --log_attr .* --tracer_entries 10000000 --exclude_files C:\Users\Max\Desktop\OneTrainer\venv\Lib\site-packages\torch -- scripts\train_ui.py
Total Entries: 59902                                                            
Use the following command to open the report:
vizviewer C:\Users\Max\Desktop\OneTrainer\result.json
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Max\Desktop\OneTrainer\venv\Scripts\viztracer.exe\__main__.py", line 7, in <module>
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\viztracer\main.py", line 671, in main
    success, err_msg = ui.run()
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\viztracer\main.py", line 317, in run
    return self.run_command()
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\viztracer\main.py", line 449, in run_command
    return self.run_code(code, main_mod.__dict__)
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\viztracer\main.py", line 361, in run_code
    exec(code, global_dict)
  File "C:\Users\Max\Desktop\OneTrainer\scripts\train_ui.py", line 6, in <module>
    from modules.ui.TrainUI import TrainUI
  File "C:\Users\Max\Desktop\OneTrainer\modules\ui\TrainUI.py", line 10, in <module>
    import torch
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\torch\__init__.py", line 1539, in <module>
    from .functional import *  # noqa: F403
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\torch\functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\torch\nn\modules\__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\torch\nn\modules\linear.py", line 7, in <module>
    from .. import functional as F
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\torch\nn\functional.py", line 3741, in <module>
    def upsample(input: Tensor, size: Optional[int] = None, scale_factor: Optional[float] = None, mode: str = "nearest", align_corners: Optional[bool] = None) -> Tensor:  # noqa: F
811,B950
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\torch\_jit_internal.py", line 889, in _overload
    _check_overload_body(func)
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\torch\_jit_internal.py", line 862, in _check_overload_body
    parsed_def = parse_def(func)
  File "C:\Users\Max\Desktop\OneTrainer\venv\lib\site-packages\torch\_sources.py", line 126, in parse_def
    py_ast = ast.parse(dedent_src)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
TypeError: CodeMonkey.compile() got an unexpected keyword argument '_feature_version'

**Comment by gaogaotiantian** [comment]
Ah thanks. The argument `_feature_version` is internal and undocumented, but CPython itself uses it. I will fix it soon.

**Comment by seniorsolt** [comment]
Seems like just adding dummy arg _feature_version works
def compile(self, source, filename, mode, flags=0, dont_inherit=False, optimize=-1, _feature_version=-1)

Taking this opportunity, I want to thank you for the tool. For a while, I was experimenting with other debuggers and even tried to write my own visualizer, but today I came across VizTracer and felt a bit sad. It already has everything implemented)

**Comment by gaogaotiantian** [comment]
I'm glad that it helped :) Yes I believe this is not hard to fix. In the meantime you can fix your local copy to make your stuff work. I will fix this in mainline soon but release takes a while too.
