### ISSUE TITLE
gevent error: RuntimeError: VizTracer: Unexpected type. Might be an event mismatch.

### ISSUE THREAD

**Issue by yihong0618** [gaogaotiantian/viztracer#531]
Hi:

when I try to use viztracer  on `[dify](https://github.com/langgenius/dify)` when gevent is open viztracer always raise error.

```
Traceback (most recent call last):
  File "/home/hyi/test/.venv/bin/viztracer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/viztracer/main.py", line 689, in main
    success, err_msg = ui.run()
                       ^^^^^^^^
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/viztracer/main.py", line 330, in run
    return self.run_command()
           ^^^^^^^^^^^^^^^^^^
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/viztracer/main.py", line 459, in run_command
    return self.run_code(code, main_mod.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/viztracer/main.py", line 374, in run_code
    exec(code, global_dict)
  File "/home/hyi/test/t.py", line 5, in <module>
    from Crypto.Cipher import AES
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/Crypto/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Crypto.Cipher._raw_ecb", """
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/Crypto/Util/_raw_api.py", line 312, in load_pycryptodome_raw_lib
    return load_lib(full_name, cdecl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/Crypto/Util/_raw_api.py", line 189, in load_lib
    cached_architecture[:] = platform.architecture()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyi/.local/share/uv/python/cpython-3.12.8-linux-aarch64-gnu/lib/python3.12/platform.py", line 721, in architecture
    fileout = _syscmd_file(executable, '')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyi/.local/share/uv/python/cpython-3.12.8-linux-aarch64-gnu/lib/python3.12/platform.py", line 670, in _syscmd_file
    output = subprocess.check_output(['file', '-b', target],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/gevent/subprocess.py", line 409, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/gevent/subprocess.py", line 819, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/gevent/subprocess.py", line 1820, in _execute_child
    data = errpipe_read.read()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/gevent/_fileobjectposix.py", line 166, in readall
    data = self.__read(DEFAULT_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyi/test/.venv/lib/python3.12/site-packages/gevent/_fileobjectposix.py", line 156, in __read
    return _read(self._fileno, n)
RuntimeError: VizTracer: Unexpected type. Might be an event mismatch.
```

I try to minimal the reproduce, you can follow

```
pip install gevent
pip install pycryptodome
```
and use `viztracer t.py` the errors happends
besides python t.py work fine

cat t.py
```python
from gevent import monkey
monkey.patch_all()
from Crypto.Cipher import AES
```

python version 3.12 3.13 all fails I did not test other versions I wonder they are the same
gevent viztracer and pycryptodome are all latest versions

**Comment by gaogaotiantian** [comment]
This is not a `viztracer` issue, it's a gevent issue. gevent secretly changes the Python frames to achieve concurrency, which breaks the assumptions of Python tracing - a return event should correspond to a call event (aka frame stack should be a stack). You can do a quick validation using the code below:

```python
import sys
frames = []

def tracefunc(frame, event, arg):
    global frames
    if event == "call":
        frames.append(frame)
    elif event == "return":
        assert frames.pop() == frame
    return tracefunc
sys.setprofile(tracefunc)

from gevent import monkey
monkey.patch_all()
from Crypto.Cipher import AES
```

The tracing part is straightforward - build a frame stack and validate that the returned frame is the same as the current one. The assertion would fail with gevent.

**Comment by yihong0618** [comment]
learned that thanks and closing it

**Comment by yihong0618** [comment]
learned that thanks and closing it
